// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.anandnet.harmonymusic.Equalizer`
extension type Equalizer._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/anandnet/harmonymusic/Equalizer');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Equalizer> type = $Equalizer$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Equalizer() {
    return _new$(_class.reference.pointer, _id_new$.pointer)
        .object<Equalizer>();
  }
}

extension Equalizer$$Methods on Equalizer {
  static final _id_openEqualizer = Equalizer._class.instanceMethodId(
    r'openEqualizer',
    r'(ILandroid/content/Context;Landroid/app/Activity;)Z',
  );

  static final _openEqualizer = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun openEqualizer(sessionId: kotlin.Int, context: android.content.Context, activity: android.app.Activity): kotlin.Boolean`
  core$_.bool openEqualizer(
    core$_.int i,
    jni$_.JObject context,
    jni$_.JObject activity,
  ) {
    final _$context = context.reference;
    final _$activity = activity.reference;
    return _openEqualizer(reference.pointer, _id_openEqualizer.pointer, i,
            _$context.pointer, _$activity.pointer)
        .boolean;
  }

  static final _id_initAudioEffect = Equalizer._class.instanceMethodId(
    r'initAudioEffect',
    r'(ILandroid/content/Context;)V',
  );

  static final _initAudioEffect = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initAudioEffect(sessionId: kotlin.Int, context: android.content.Context): kotlin.Unit`
  void initAudioEffect(
    core$_.int i,
    jni$_.JObject context,
  ) {
    final _$context = context.reference;
    _initAudioEffect(reference.pointer, _id_initAudioEffect.pointer, i,
            _$context.pointer)
        .check();
  }

  static final _id_endAudioEffect = Equalizer._class.instanceMethodId(
    r'endAudioEffect',
    r'(ILandroid/content/Context;)V',
  );

  static final _endAudioEffect = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun endAudioEffect(sessionId: kotlin.Int, context: android.content.Context): kotlin.Unit`
  void endAudioEffect(
    core$_.int i,
    jni$_.JObject context,
  ) {
    final _$context = context.reference;
    _endAudioEffect(
            reference.pointer, _id_endAudioEffect.pointer, i, _$context.pointer)
        .check();
  }
}

final class $Equalizer$Type$ extends jni$_.JType<Equalizer> {
  @jni$_.internal
  const $Equalizer$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/anandnet/harmonymusic/Equalizer;';
}

/// from: `com.anandnet.harmonymusic.SDKInt$Companion`
extension type SDKInt$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/anandnet/harmonymusic/SDKInt$Companion');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SDKInt$Companion> type = $SDKInt$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SDKInt$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(_class.reference.pointer, _id_new$.pointer,
            _$defaultConstructorMarker.pointer)
        .object<SDKInt$Companion>();
  }
}

extension SDKInt$Companion$$Methods on SDKInt$Companion {
  static final _id_get$sDKInt = SDKInt$Companion._class.instanceMethodId(
    r'getSDKInt',
    r'()I',
  );

  static final _get$sDKInt = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun getSDKInt(): kotlin.Int`
  core$_.int get sDKInt {
    return _get$sDKInt(reference.pointer, _id_get$sDKInt.pointer).integer;
  }
}

final class $SDKInt$Companion$Type$ extends jni$_.JType<SDKInt$Companion> {
  @jni$_.internal
  const $SDKInt$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/anandnet/harmonymusic/SDKInt$Companion;';
}

/// from: `com.anandnet.harmonymusic.SDKInt`
extension type SDKInt._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/anandnet/harmonymusic/SDKInt');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SDKInt> type = $SDKInt$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/anandnet/harmonymusic/SDKInt$Companion;',
  );

  /// from: `static public final com.anandnet.harmonymusic.SDKInt$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static SDKInt$Companion get Companion =>
      _id_Companion.get(_class, SDKInt$Companion.type) as SDKInt$Companion;

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory SDKInt() {
    return _new$(_class.reference.pointer, _id_new$.pointer).object<SDKInt>();
  }
}

final class $SDKInt$Type$ extends jni$_.JType<SDKInt> {
  @jni$_.internal
  const $SDKInt$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/anandnet/harmonymusic/SDKInt;';
}
